-- ============================================================
--  ArtBloom — Supabase PostgreSQL Schema
--  Run this in the Supabase SQL Editor
-- ============================================================

-- Enable pgcrypto for UUIDs if needed (optional)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── users ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.users (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name           VARCHAR(50)     NOT NULL,
  last_name            VARCHAR(50)     NOT NULL,
  username             VARCHAR(30)     NOT NULL UNIQUE,
  email                VARCHAR(191)    NOT NULL UNIQUE,
  password             VARCHAR(255)    NOT NULL, -- Might be replaced by Supabase Auth (auth.users) in the future
  role                 TEXT            NOT NULL DEFAULT 'parent' CHECK (role IN ('parent','admin')),
  account_status       TEXT            NOT NULL DEFAULT 'active' CHECK (account_status IN ('active','suspended','pending_verification','deactivated')),
  suspension_reason    TEXT,
  suspension_end_date  TIMESTAMP WITH TIME ZONE,
  avatar_url           VARCHAR(500)    NOT NULL DEFAULT 'https://res.cloudinary.com/demo/image/upload/v1/art-showcase/avatars/default.png',
  avatar_public_id     VARCHAR(255),
  bio                  VARCHAR(300)    NOT NULL DEFAULT '',
  location             VARCHAR(100)    NOT NULL DEFAULT '',
  website              VARCHAR(255)    NOT NULL DEFAULT '',
  total_likes_given    INT             NOT NULL DEFAULT 0,
  total_comments_given INT             NOT NULL DEFAULT 0,
  forum_post_count     INT             NOT NULL DEFAULT 0,
  email_verified       BOOLEAN         NOT NULL DEFAULT false,
  last_login           TIMESTAMP WITH TIME ZONE,
  login_attempts       SMALLINT        NOT NULL DEFAULT 0,
  lock_until           TIMESTAMP WITH TIME ZONE,
  notif_email_comment  BOOLEAN         NOT NULL DEFAULT true,
  notif_email_like     BOOLEAN         NOT NULL DEFAULT false,
  notif_email_forum    BOOLEAN         NOT NULL DEFAULT true,
  theme                TEXT            NOT NULL DEFAULT 'system' CHECK (theme IN ('light','dark','system')),
  created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── children ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.children (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id         BIGINT        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  display_name      VARCHAR(40)   NOT NULL,
  date_of_birth     DATE          NOT NULL,
  age_group         TEXT          CHECK (age_group IN ('toddler','early_childhood','middle_childhood','tween')),
  avatar_url        VARCHAR(500)  NOT NULL DEFAULT 'https://res.cloudinary.com/demo/image/upload/v1/art-showcase/avatars/child_default.png',
  avatar_public_id  VARCHAR(255),
  bio               VARCHAR(200)  NOT NULL DEFAULT '',
  art_interests     JSONB         DEFAULT '[]'::jsonb,
  favorite_colors   JSONB         DEFAULT '[]'::jsonb,
  privacy_level     TEXT          NOT NULL DEFAULT 'community' CHECK (privacy_level IN ('public','community','private')),
  total_uploads     INT           NOT NULL DEFAULT 0,
  total_likes       INT           NOT NULL DEFAULT 0,
  total_comments    INT           NOT NULL DEFAULT 0,
  featured_count    INT           NOT NULL DEFAULT 0,
  consent_given     BOOLEAN       NOT NULL DEFAULT false,
  consent_date      TIMESTAMP WITH TIME ZONE,
  is_active         BOOLEAN       NOT NULL DEFAULT true,
  deactivated_at    TIMESTAMP WITH TIME ZONE,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── artworks ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.artworks (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  child_id            BIGINT        NOT NULL REFERENCES public.children(id) ON DELETE CASCADE,
  parent_id           BIGINT        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title               VARCHAR(100)  NOT NULL,
  description         VARCHAR(500)  NOT NULL DEFAULT '',
  category            TEXT          NOT NULL CHECK (category IN ('painting','drawing','craft','sculpture','digital','mixed_media','photography','other')),
  medium              VARCHAR(80)   NOT NULL DEFAULT '',
  tags                JSONB         DEFAULT '[]'::jsonb,
  image_original_url  VARCHAR(500)  NOT NULL,
  image_original_pid  VARCHAR(255)  NOT NULL,
  image_medium_url    VARCHAR(500),
  image_thumb_url     VARCHAR(500),
  moderation_status   TEXT          NOT NULL DEFAULT 'pending' CHECK (moderation_status IN ('pending','approved','rejected','flagged')),
  moderation_notes    TEXT          NOT NULL DEFAULT '',
  moderated_by        BIGINT,
  moderated_at        TIMESTAMP WITH TIME ZONE,
  like_count          INT           NOT NULL DEFAULT 0,
  view_count          INT           NOT NULL DEFAULT 0,
  share_count         INT           NOT NULL DEFAULT 0,
  report_count        INT           NOT NULL DEFAULT 0,
  is_published        BOOLEAN       NOT NULL DEFAULT false,
  is_featured         BOOLEAN       NOT NULL DEFAULT false,
  featured_at         TIMESTAMP WITH TIME ZONE,
  child_story         VARCHAR(300)  NOT NULL DEFAULT '',
  creation_date       DATE,
  created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── artwork_likes ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.artwork_likes (
  artwork_id BIGINT NOT NULL REFERENCES public.artworks(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  PRIMARY KEY (artwork_id, user_id)
);

-- ── comments ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.comments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artwork_id         BIGINT        NOT NULL REFERENCES public.artworks(id) ON DELETE CASCADE,
  author_id          BIGINT        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_comment_id  BIGINT,
  text               VARCHAR(500)  NOT NULL,
  moderation_status  TEXT          NOT NULL DEFAULT 'pending' CHECK (moderation_status IN ('pending','approved','rejected','flagged')),
  moderated_by       BIGINT,
  moderated_at       TIMESTAMP WITH TIME ZONE,
  moderation_note    VARCHAR(300)  NOT NULL DEFAULT '',
  reaction_count     INT           NOT NULL DEFAULT 0,
  report_count       INT           NOT NULL DEFAULT 0,
  reply_count        INT           NOT NULL DEFAULT 0,
  is_deleted         BOOLEAN       NOT NULL DEFAULT false,
  deleted_at         TIMESTAMP WITH TIME ZONE,
  deleted_by         BIGINT,
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── forum_posts ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.forum_posts (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id          BIGINT        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  title              VARCHAR(150)  NOT NULL,
  body               TEXT          NOT NULL,
  category           TEXT          NOT NULL CHECK (category IN ('tips_and_advice','art_techniques','child_development','materials_and_supplies','showcase_feedback','events_and_activities','general_discussion','announcements')),
  tags               JSONB         DEFAULT '[]'::jsonb,
  upvote_count       INT           NOT NULL DEFAULT 0,
  view_count         INT           NOT NULL DEFAULT 0,
  comment_count      INT           NOT NULL DEFAULT 0,
  report_count       INT           NOT NULL DEFAULT 0,
  is_pinned          BOOLEAN       NOT NULL DEFAULT false,
  is_announcement    BOOLEAN       NOT NULL DEFAULT false,
  is_closed          BOOLEAN       NOT NULL DEFAULT false,
  is_locked          BOOLEAN       NOT NULL DEFAULT false,
  moderation_status  TEXT          NOT NULL DEFAULT 'approved' CHECK (moderation_status IN ('pending','approved','rejected','flagged')),
  moderated_by       BIGINT,
  moderated_at       TIMESTAMP WITH TIME ZONE,
  is_deleted         BOOLEAN       NOT NULL DEFAULT false,
  deleted_at         TIMESTAMP WITH TIME ZONE,
  last_activity_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── forum_post_upvotes ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.forum_post_upvotes (
  post_id    BIGINT NOT NULL REFERENCES public.forum_posts(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  PRIMARY KEY (post_id, user_id)
);

-- ── forum_comments ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.forum_comments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id            BIGINT        NOT NULL REFERENCES public.forum_posts(id) ON DELETE CASCADE,
  author_id          BIGINT        NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  parent_comment_id  BIGINT,
  text               VARCHAR(1000) NOT NULL,
  upvote_count       INT           NOT NULL DEFAULT 0,
  reply_count        INT           NOT NULL DEFAULT 0,
  report_count       INT           NOT NULL DEFAULT 0,
  moderation_status  TEXT          NOT NULL DEFAULT 'approved' CHECK (moderation_status IN ('pending','approved','rejected','flagged')),
  is_deleted         BOOLEAN       NOT NULL DEFAULT false,
  deleted_at         TIMESTAMP WITH TIME ZONE,
  created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ── Create a trigger function for updated_at ─────────────────
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

-- ── Apply triggers to all tables ─────────────────────────────
CREATE TRIGGER update_users_modtime BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_children_modtime BEFORE UPDATE ON public.children FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_artworks_modtime BEFORE UPDATE ON public.artworks FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_comments_modtime BEFORE UPDATE ON public.comments FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_forum_posts_modtime BEFORE UPDATE ON public.forum_posts FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_forum_comments_modtime BEFORE UPDATE ON public.forum_comments FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- ── Default admin user (password will need hashing for Supabase auth later) ──
INSERT INTO public.users 
  (first_name, last_name, username, email, password, role, account_status, email_verified)
VALUES
  ('Admin', 'User', 'admin', 'admin@artshowcase.com', 'hashed_pass_here', 'admin', 'active', true)
ON CONFLICT (username) DO NOTHING;
